// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Tool'], function(Tool) {
    Tool.Media = (function(_super) {
      __extends(Media, _super);

      Media.label = 'Media';

      Media.description = '';

      Media.iconURL = 'image.png';

      Media.favorite = true;

      Media.category = '';

      Media.cursor = {
        position: {
          x: 0,
          y: 0
        },
        name: 'default',
        icon: 'image'
      };

      function Media() {
        Media.__super__.constructor.call(this, R.RMedia);
        return;
      }

      Media.prototype.end = function(event, from) {
        if (from == null) {
          from = R.me;
        }
        if (Media.__super__.end.call(this, event, from)) {
          R.RMedia.initialize(R.currentPaths[from].bounds);
          delete R.currentPaths[from];
        }
      };

      return Media;

    })(Tool.Item);
    new Tool.Media();
    return Tool.Media;
  });

}).call(this);

//# sourceMappingURL=MediaTool.map
