// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Tool'], function(Tool) {
    Tool.Select = (function(_super) {
      __extends(Select, _super);

      Select.label = 'Select';

      Select.description = '';

      Select.iconURL = 'cursor.png';

      Select.cursor = {
        position: {
          x: 0,
          y: 0
        },
        name: 'crosshair',
        icon: 'cursor'
      };

      Select.drawItems = false;

      Select.hitOptions = {
        stroke: true,
        fill: true,
        handles: true,
        segments: true,
        curves: true,
        selected: true,
        tolerance: 5
      };

      Select.deselectAll = function() {
        if (R.selectedItems.length > 0) {
          R.commandManager.add(new R.DeselectCommand(), true);
        }
        P.project.activeLayer.selected = false;
      };

      function Select() {
        Select.__super__.constructor.call(this, true);
        this.selectedItem = null;
        return;
      }

      Select.prototype.select = function(deselectItems, updateParameters) {
        if (deselectItems == null) {
          deselectItems = false;
        }
        if (updateParameters == null) {
          updateParameters = true;
        }
        Select.__super__.select.call(this, false, updateParameters);
      };

      Select.prototype.updateParameters = function() {
        R.controllerManager.updateParametersForSelectedItems();
      };

      Select.prototype.createSelectionRectangle = function(event) {
        var bounds, item, itemsToHighlight, name, rectangle, rectanglePath, _ref;
        rectangle = new P.Rectangle(event.downPoint, event.point);
        if (R.currentPaths[R.me] != null) {
          Utils.Rectangle.updatePathRectangle(R.currentPaths[R.me], rectangle);
        } else {
          rectanglePath = new P.Path.Rectangle(rectangle);
          rectanglePath.name = 'select tool selection rectangle';
          rectanglePath.strokeColor = R.selectionBlue;
          rectanglePath.strokeScaling = false;
          rectanglePath.dashArray = [10, 4];
          R.selectionLayer.addChild(rectanglePath);
          R.currentPaths[R.me] = rectanglePath;
        }
        itemsToHighlight = [];
        _ref = R.items;
        for (name in _ref) {
          item = _ref[name];
          item.unhighlight();
          bounds = item.getBounds();
          if (bounds.intersects(rectangle)) {
            item.highlight();
            console.log(item.highlightRectangle.index);
          }
          if (rectangle.area === 0) {
            break;
          }
        }
      };

      Select.prototype.begin = function(event) {
        var hitResult, name, path, _base, _ref, _ref1, _ref2;
        if (event.event.which === 2) {
          return;
        }
        console.log('begin select');
        R.logElapsedTime();
        _ref = R.paths;
        for (name in _ref) {
          path = _ref[name];
          path.prepareHitTest();
        }
        hitResult = P.project.hitTest(event.point, this.constructor.hitOptions);
        _ref1 = R.paths;
        for (name in _ref1) {
          path = _ref1[name];
          path.finishHitTest();
        }
        if (hitResult && (hitResult.item.controller != null)) {
          this.selectedItem = hitResult.item.controller;
          if (!event.modifiers.shift) {
            if (R.selectedItems.length > 0) {
              if (R.selectedItems.indexOf((_ref2 = hitResult.item) != null ? _ref2.controller : void 0) < 0) {
                R.commandManager.add(new R.DeselectCommand(), true);
              }
            }
          } else {
            R.tools['Screenshot'].checkRemoveScreenshotRectangle(hitResult.item.controller);
          }
          if (typeof (_base = hitResult.item.controller).beginSelect === "function") {
            _base.beginSelect(event);
          }
        } else {
          Tool.Select.deselectAll();
          this.createSelectionRectangle(event);
        }
        R.logElapsedTime();
      };

      Select.prototype.update = function(event) {
        if (!R.currentPaths[R.me] && (this.selectedItem != null)) {
          this.selectedItem.updateSelect(event);
        } else {
          this.createSelectionRectangle(event);
        }
      };

      Select.prototype.end = function(event) {
        var child, i, item, itemsAreSiblings, itemsToSelect, lock, locksToSelect, name, parent, rectangle, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
        if (!R.currentPaths[R.me]) {
          this.selectedItem.endSelect(event);
          this.selectedItem = null;
        } else {
          rectangle = new P.Rectangle(event.downPoint, event.point);
          itemsToSelect = [];
          locksToSelect = [];
          _ref = R.items;
          for (name in _ref) {
            item = _ref[name];
            if (item.getBounds().intersects(rectangle)) {
              if (Lock.prototype.isPrototypeOf(item)) {
                locksToSelect.push(item);
              } else {
                itemsToSelect.push(item);
              }
            }
          }
          if (itemsToSelect.length === 0) {
            itemsToSelect = locksToSelect;
          }
          if (itemsToSelect.length > 0) {
            itemsAreSiblings = true;
            parent = itemsToSelect[0].group.parent;
            for (_i = 0, _len = itemsToSelect.length; _i < _len; _i++) {
              item = itemsToSelect[_i];
              if (item.group.parent !== parent) {
                itemsAreSiblings = false;
                break;
              }
            }
            if (!itemsAreSiblings) {
              for (_j = 0, _len1 = locksToSelect.length; _j < _len1; _j++) {
                lock = locksToSelect[_j];
                _ref1 = lock.children();
                for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
                  child = _ref1[_k];
                  Utils.Array.remove(itemsToSelect, child);
                }
              }
              itemsToSelect = itemsToSelect.concat(locksToSelect);
            }
            if (rectangle.area === 0) {
              itemsToSelect = [itemsToSelect[0]];
            }
            R.commandManager.add(new R.SelectCommand(itemsToSelect), true);
            i = itemsToSelect.length - 1;
            while (i >= 0) {
              item = itemsToSelect[i];
              if (!item.isSelected()) {
                Utils.Array.remove(itemsToSelect, item);
              }
              i--;
            }
          }
          R.currentPaths[R.me].remove();
          delete R.currentPaths[R.me];
          _ref2 = R.items;
          for (name in _ref2) {
            item = _ref2[name];
            item.unhighlight();
          }
        }
        console.log('end select');
        R.logElapsedTime();
      };

      Select.prototype.doubleClick = function(event) {
        var item, _i, _len, _ref;
        _ref = R.selectedItems;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (typeof item.doubleClick === "function") {
            item.doubleClick(event);
          }
        }
      };

      Select.prototype.disableSnap = function() {
        return R.currentPaths[R.me] != null;
      };

      Select.prototype.keyUp = function(event) {
        var delta, item, selectedItems, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
        if ((_ref = event.key) === 'left' || _ref === 'right' || _ref === 'up' || _ref === 'down') {
          delta = event.modifiers.shift ? 50 : event.modifiers.option ? 5 : 1;
        }
        switch (event.key) {
          case 'right':
            _ref1 = R.selectedItems;
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              item = _ref1[_i];
              item.moveBy(new P.Point(delta, 0), true);
            }
            break;
          case 'left':
            _ref2 = R.selectedItems;
            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
              item = _ref2[_j];
              item.moveBy(new P.Point(-delta, 0), true);
            }
            break;
          case 'up':
            _ref3 = R.selectedItems;
            for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
              item = _ref3[_k];
              item.moveBy(new P.Point(0, -delta), true);
            }
            break;
          case 'down':
            _ref4 = R.selectedItems;
            for (_l = 0, _len3 = _ref4.length; _l < _len3; _l++) {
              item = _ref4[_l];
              item.moveBy(new P.Point(0, delta), true);
            }
            break;
          case 'escape':
            Tool.Select.deselectAll();
            break;
          case 'delete':
          case 'backspace':
            selectedItems = R.selectedItems.slice();
            for (_m = 0, _len4 = selectedItems.length; _m < _len4; _m++) {
              item = selectedItems[_m];
              if (((_ref5 = item.selectionState) != null ? _ref5.segment : void 0) != null) {
                item.deletePointCommand();
              } else {
                item.deleteCommand();
              }
            }
        }
      };

      return Select;

    })(Tool);
    new Tool.Select();
    return Tool.Select;
  });

}).call(this);

//# sourceMappingURL=SelectTool.map
