// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['utils', 'RShape'], function(utils, RShape) {
    var Checkpoint;
    Checkpoint = (function(_super) {
      __extends(Checkpoint, _super);

      function Checkpoint() {
        return Checkpoint.__super__.constructor.apply(this, arguments);
      }

      Checkpoint.Shape = paper.Path.Rectangle;

      Checkpoint.rname = 'Checkpoint';

      Checkpoint.rdescription = "Draw checkpoints on a lock with a Racer to create a race\n(the players must go through each checkpoint as fast as possible, with the car tool).";

      Checkpoint.category = 'Video game/Racer';

      Checkpoint.squareByDefault = false;

      Checkpoint.initializeParameters = function() {
        return {};
      };

      Checkpoint.parameters = Checkpoint.initializeParameters();

      Checkpoint.prototype.initialize = function() {
        var _base;
        this.data.type = 'checkpoint';
        if (this.lock != null) {
          if (this.lock.checkpoints.indexOf(this) < 0) {
            this.lock.checkpoints.push(this);
          }
          if ((_base = this.data).checkpointNumber == null) {
            _base.checkpointNumber = this.game.checkpoints.indexOf(this);
          }
        } else {
          g.romanesco_alert('A checkpoint must be placed on a lock', 'error');
          this.remove();
        }
      };

      Checkpoint.prototype.createShape = function() {
        this.data.strokeColor = 'rgb(150,30,30)';
        this.data.fillColor = null;
        this.shape = this.addPath(new Path.Rectangle(this.rectangle));
        this.text = this.addPath(new PointText(this.rectangle.center.add(0, 4)));
        this.text.content = this.data.checkpointNumber != null ? 'Checkpoint ' + this.data.checkpointNumber : 'Checkpoint';
        this.text.justification = 'center';
      };

      Checkpoint.prototype.contains = function(point) {
        var delta;
        delta = point.subtract(this.rectangle.center);
        delta.rotation = -this.rotation;
        return this.rectangle.contains(this.rectangle.center.add(delta));
      };

      Checkpoint.prototype.remove = function() {
        var _ref;
        if ((_ref = this.lock) != null) {
          _ref.checkpoints.remove(this);
        }
        Checkpoint.__super__.remove.call(this);
      };

      return Checkpoint;

    })(RShape);
    g.pathClasses.push(Checkpoint);
    return Checkpoint;
  });

}).call(this);

//# sourceMappingURL=Checkpoint.map
