// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['utils', 'RShape'], function(utils, RShape) {
    var EllipseShape;
    EllipseShape = (function(_super) {
      __extends(EllipseShape, _super);

      function EllipseShape() {
        return EllipseShape.__super__.constructor.apply(this, arguments);
      }

      EllipseShape.Shape = paper.Path.Ellipse;

      EllipseShape.category = 'Shape';

      EllipseShape.rname = 'Ellipse';

      EllipseShape.rdescription = "Simple ellipse, circle by default (use shift key to draw an ellipse).\nUse special key (command on a mac, control otherwise) to avoid the shape to be centered on the first point.";

      EllipseShape.iconURL = 'static/images/icons/inverted/circle.png';

      EllipseShape.iconAlt = 'circle';

      EllipseShape.squareByDefault = true;

      EllipseShape.centerByDefault = true;

      return EllipseShape;

    })(RShape);
    g.pathClasses.push(g.EllipseShape);
    return EllipseShape;
  });

}).call(this);

//# sourceMappingURL=EllipseShape.map
