// Generated by CoffeeScript 1.7.1
(function() {
  define(['Commands/Command', 'Tools/ItemTool'], function(Command, ItemTool) {
    var Item;
    console.log('Item');
    Item = (function() {
      Item.hitOptions = {
        segments: true,
        stroke: true,
        fill: true,
        selected: true,
        tolerance: 5
      };

      Item.zIndexSortStop = function(event, ui) {
        var item, nextItemJ, previousItemJ, previouslySelectedItems, rItem, _i, _len;
        previouslySelectedItems = R.selectedItems;
        R.tools.select.deselectAll()();
        rItem = R.items[ui.item.attr("data-pk")];
        nextItemJ = ui.item.next();
        if (nextItemJ.length > 0) {
          rItem.insertAbove(R.items[nextItemJ.attr("data-pk")], null, true);
        } else {
          previousItemJ = ui.item.prev();
          if (previousItemJ.length > 0) {
            rItem.insertBelow(R.items[previousItemJ.attr("data-pk")], null, true);
          }
        }
        for (_i = 0, _len = previouslySelectedItems.length; _i < _len; _i++) {
          item = previouslySelectedItems[_i];
          item.select();
        }
      };

      Item.addItemToStage = function(item) {
        Item.addItemTo(item);
      };

      Item.addItemTo = function(item, lock) {
        var group, parent, wasSelected;
        if (lock == null) {
          lock = null;
        }
        wasSelected = item.isSelected();
        if (wasSelected) {
          item.deselect();
        }
        group = lock ? lock.group : R.view.mainLayer;
        group.addChild(item.group);
        item.lock = lock;
        Utils.Array.remove(item.sortedItems, item);
        parent = lock || R.sidebar;
        if (Item.Div.prototype.isPrototypeOf(item)) {
          item.sortedItems = parent.sortedDivs;
          parent.itemListsJ.find(".rDiv-list").append(item.liJ);
        } else if (R.RPath.prototype.isPrototypeOf(item)) {
          item.sortedItems = parent.sortedPaths;
          parent.itemListsJ.find(".rPath-list").append(item.liJ);
        } else {
          console.error("Error: the item is neither an Div nor an RPath");
        }
        item.updateZIndex();
        if (wasSelected) {
          item.select();
        }
      };

      Item.initializeParameters = function() {
        var parameters;
        console.log('Item.initializeParameters');
        parameters = {
          'Items': {
            align: R.parameters.align,
            distribute: R.parameters.distribute,
            "delete": R.parameters["delete"]
          },
          'Style': {
            strokeWidth: R.parameters.strokeWidth,
            strokeColor: R.parameters.strokeColor,
            fillColor: R.parameters.fillColor
          },
          'Pos. & size': {
            position: {
              "default": '',
              label: 'Position',
              onChange: function() {},
              onFinishChange: this.onPositionFinishChange
            },
            size: {
              "default": '',
              label: 'P.Size',
              onChange: function() {},
              onFinishChange: this.onSizeFinishChange
            }
          }
        };
        return parameters;
      };

      Item.parameters = Item.initializeParameters();

      Item.create = function(duplicateData) {
        var copy;
        copy = new this(duplicateData);
        if (!this.socketAction) {
          copy.save(false);
          R.socket.emit("bounce", {
            itemClass: this.name,
            "function": "create",
            "arguments": [duplicateData]
          });
        }
        return copy;
      };

      function Item(data, pk) {
        var _ref;
        this.data = data;
        this.pk = pk;
        if (this.pk != null) {
          this.setPK(this.pk, true);
          R.commandManager.loadItem(this);
        } else {
          this.id = ((_ref = this.data) != null ? _ref.id : void 0) != null ? this.data.id : Math.random();
          R.items[this.id] = this;
        }
        if (this.data != null) {
          this.secureData();
        } else {
          this.data = new Object();
          R.controllerManager.updateItemData(this);
        }
        if (this.rectangle == null) {
          this.rectangle = null;
        }
        this.selectionState = null;
        this.group = new P.Group();
        this.group.name = "group";
        this.group.controller = this;
        return;
      }

      Item.prototype.secureData = function() {
        var name, parameter, value, _ref;
        _ref = this.constructor.parameters;
        for (name in _ref) {
          parameter = _ref[name];
          if (parameter.secure != null) {
            this.data[name] = parameter.secure(this.data, parameter);
          } else {
            value = this.data[name];
            if ((value != null) && (parameter.min != null) && (parameter.max != null)) {
              if (value < parameter.min || value > parameter.max) {
                this.data[name] = Utils.clamp(parameter.min, value, parameter.max);
              }
            }
          }
        }
      };

      Item.prototype.setParameter = function(name, value, update) {
        if (this.data[name] === 'undefined') {
          return;
        }
        this.data[name] = value;
        this.changed = name;
        if (!this.socketAction) {
          if (update) {
            this.update(name);
          }
          R.socket.emit("bounce", {
            itemPk: this.pk,
            "function": "setParameter",
            "arguments": [name, value, false, false]
          });
        }
      };

      Item.prototype.prepareHitTest = function() {};

      Item.prototype.finishHitTest = function() {};

      Item.prototype.setRectangle = function(rectangle, update) {
        if (update == null) {
          update = true;
        }
        if (!P.Rectangle.prototype.isPrototypeOf(rectangle)) {
          rectangle = new P.Rectangle(rectangle);
        }
        this.rectangle = rectangle;
        if (!this.socketAction) {
          if (update) {
            this.update('rectangle');
          }
          R.socket.emit("bounce", {
            itemPk: this.pk,
            "function": "setRectangle",
            "arguments": [this.rectangle, false]
          });
        }
      };

      Item.prototype.validatePosition = function() {
        return Item.Lock.validatePosition(this);
      };

      Item.prototype.moveTo = function(position, update) {
        var delta;
        if (!P.Point.prototype.isPrototypeOf(position)) {
          position = new P.Point(position);
        }
        delta = position.subtract(this.rectangle.center);
        this.rectangle.center = position;
        this.group.translate(delta);
        if (!this.socketAction) {
          if (update) {
            this.update('position');
          }
          R.socket.emit("bounce", {
            itemPk: this.pk,
            "function": "moveTo",
            "arguments": [position, false]
          });
        }
      };

      Item.prototype.translate = function(delta, update) {
        this.moveTo(this.rectangle.center.add(delta), update);
      };

      Item.prototype.scale = function(scale, center, update) {
        this.setRectangle(this.rectangle.scaleFromCenter(scale, center), update);
      };

      Item.prototype.getData = function() {
        var data;
        data = jQuery.extend({}, this.data);
        data.rectangle = this.rectangle.toJSON();
        data.rotation = this.rotation;
        return data;
      };

      Item.prototype.getStringifiedData = function() {
        return JSON.stringify(this.getData());
      };

      Item.prototype.getBounds = function() {
        return this.rectangle;
      };

      Item.prototype.getDrawingBounds = function() {
        return this.rectangle.expand(this.data.strokeWidth);
      };

      Item.prototype.highlight = function() {
        if (this.highlightRectangle != null) {
          Utils.Rectangle.updatePathRectangle(this.highlightRectangle, this.getBounds());
          return;
        }
        this.highlightRectangle = new P.Path.Rectangle(this.getBounds());
        this.highlightRectangle.strokeColor = R.selectionBlue;
        this.highlightRectangle.strokeScaling = false;
        this.highlightRectangle.dashArray = [4, 10];
        R.view.selectionLayer.addChild(this.highlightRectangle);
      };

      Item.prototype.unhighlight = function() {
        if (this.highlightRectangle == null) {
          return;
        }
        this.highlightRectangle.remove();
        this.highlightRectangle = null;
      };

      Item.prototype.getPk = function() {
        return this.pk || this.id;
      };

      Item.prototype.setPK = function(pk, loading) {
        this.pk = pk;
        if (loading == null) {
          loading = false;
        }
        if (this.id != null) {
          R.commandManager.setItemPk(this.id, this.pk);
        }
        R.items[this.pk] = this;
        delete R.items[this.id];
        if (!loading && !this.socketAction) {
          R.socket.emit("bounce", {
            itemPk: this.id,
            "function": "setPK",
            "arguments": [this.pk]
          });
        }
      };

      Item.prototype.isSelected = function() {
        return this.selectionRectangle != null;
      };

      Item.prototype.select = function() {
        var _ref;
        if (this.selected) {
          return false;
        }
        this.selected = true;
        if ((_ref = this.lock) != null) {
          _ref.deselect();
        }
        this.selectionState = {
          move: true
        };
        R.s = this;
        R.selectedItems.push(this);
        R.tools.select.updateSelectionRectangle();
        R.controllerManager.updateParametersForSelectedItems();
        R.rasterizer.selectItem(this);
        this.zindex = this.group.index;
        R.view.selectionLayer.addChild(this.group);
        return true;
      };

      Item.prototype.deselect = function() {
        if (!this.selected) {
          return false;
        }
        this.selected = false;
        Utils.Array.remove(R.selectedItems, this);
        R.tools.select.updateSelectionRectangle();
        R.controllerManager.updateParametersForSelectedItems();
        if (this.group != null) {
          R.rasterizer.deselectItem(this);
          if (!this.lock) {
            this.group = R.view.mainLayer.insertChild(this.zindex, this.group);
          } else {
            this.group = this.lock.group.insertChild(this.zindex, this.group);
          }
        }
        return true;
      };

      Item.prototype.remove = function() {
        var _ref;
        R.commandManager.unloadItem(this);
        if (!this.group) {
          return;
        }
        this.group.remove();
        this.group = null;
        this.deselect();
        if ((_ref = this.highlightRectangle) != null) {
          _ref.remove();
        }
        if (this.pk != null) {
          delete R.items[this.pk];
        } else {
          delete R.items[this.id];
        }
      };

      Item.prototype.finish = function() {
        if (this.rectangle.area === 0) {
          this.remove();
          return false;
        }
        return true;
      };

      Item.prototype.save = function(addCreateCommand) {
        if (addCreateCommand) {
          R.commandManager.add(new Command.CreateItem(this));
        }
      };

      Item.prototype.saveCallback = function() {};

      Item.prototype.addUpdateFunctionAndArguments = function(args, type) {
        args.push({
          "function": this.getUpdateFunction(type),
          "arguments": this.getUpdateArguments(type)
        });
      };

      Item.prototype["delete"] = function() {
        if (!this.socketAction) {
          R.socket.emit("bounce", {
            itemPk: this.pk,
            "function": "delete",
            "arguments": []
          });
        }
        this.pk = null;
      };

      Item.prototype.deleteCommand = function() {
        R.commandManager.add(new Command.DeleteItem(this), true);
      };

      Item.prototype.getDuplicateData = function() {
        return {
          data: this.getData(),
          rectangle: this.rectangle,
          pk: this.getPk()
        };
      };

      Item.prototype.duplicateCommand = function() {
        R.commandManager.add(new Command.DuplicateItem(this), true);
      };

      Item.prototype.removeDrawing = function() {
        var _ref;
        if (((_ref = this.drawing) != null ? _ref.parent : void 0) == null) {
          return;
        }
        this.drawingRelativePosition = this.drawing.position.subtract(this.rectangle.center);
        this.drawing.remove();
      };

      Item.prototype.replaceDrawing = function() {
        var _ref;
        if ((this.drawing == null) || (this.drawingRelativePosition == null)) {
          return;
        }
        if ((_ref = this.raster) != null) {
          _ref.remove();
        }
        this.group.addChild(this.drawing);
        this.drawing.position = this.rectangle.center.add(this.drawingRelativePosition);
        this.drawingRelativePosition = null;
      };

      Item.prototype.rasterize = function() {
        if ((this.raster != null) || (this.drawing == null)) {
          return;
        }
        if (!R.rasterizer.rasterizeItems) {
          return;
        }
        this.raster = this.drawing.rasterize();
        this.group.addChild(this.raster);
        this.raster.sendToBack();
        this.removeDrawing();
      };

      return Item;

    })();
    return Item;
  });

}).call(this);
