// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Items/Item', 'UI/Modal'], function(Item, Modal) {
    var Link, Lock, VideoGame, Website;
    Lock = (function(_super) {
      __extends(Lock, _super);

      Lock.label = 'Lock';

      Lock.object_type = 'lock';

      Lock.initialize = function(rectangle) {
        var modal, radioButtons, radioGroupJ, siteURLJ, siteUrlExtractor, submit;
        submit = function(data) {
          var lock;
          switch (data.object_type) {
            case 'lock':
              lock = new Lock(rectangle, data);
              break;
            case 'website':
              lock = new Website(rectangle, data);
              break;
            case 'video-game':
              lock = new VideoGame(rectangle, data);
              break;
            case 'link':
              lock = new Link(rectangle, data);
          }
          lock.save(true);
          lock.update('rectangle');
          lock.select();
        };
        modal = Modal.createModal({
          title: 'Create a locked area',
          submit: submit
        });
        radioButtons = [
          {
            value: 'lock',
            checked: true,
            label: 'Create simple lock',
            submitShortcut: true,
            linked: []
          }, {
            value: 'link',
            checked: false,
            label: 'Create link',
            linked: ['linkName', 'url', 'message']
          }, {
            value: 'website',
            checked: false,
            label: 'Create  website (® x2)',
            linked: ['restrictArea', 'disableToolbar', 'siteName']
          }
        ];
        radioGroupJ = modal.addRadioGroup({
          name: 'object_type',
          radioButtons: radioButtons
        });
        modal.addCheckbox({
          name: 'restrictArea',
          label: 'Restrict area',
          helpMessage: "Users visiting your website will not be able to go out of the site boundaries."
        });
        modal.addCheckbox({
          name: 'disableToolbar',
          label: 'Disable toolbar',
          helpMessage: "Users will not have access to the toolbar on your site."
        });
        modal.addTextInput({
          name: 'linkName',
          label: 'Site name',
          type: 'text',
          placeholder: 'Site name'
        });
        modal.addTextInput({
          name: 'url',
          placeholder: 'http://',
          type: 'url',
          "class": 'url',
          label: 'URL'
        });
        siteURLJ = $("<div class=\"form-group siteName\">\n	<label for=\"modalSiteName\">Site name</label>\n	<div class=\"input-group\">\n		<span class=\"input-group-addon\">romanesco.city/#</span>\n		<input id=\"modalSiteName\" type=\"text\" class=\"name form-control\" placeholder=\"Site name\">\n	</div>\n</div>");
        siteUrlExtractor = function(data, siteURLJ) {
          data.siteURL = siteURLJ.find("#modalSiteName").val();
          return true;
        };
        modal.addCustomContent({
          name: 'siteName',
          divJ: siteURLJ,
          extractor: siteUrlExtractor
        });
        modal.addTextInput({
          name: 'message',
          label: 'Enter the message you want others to see when they look at this link.',
          type: 'text',
          placeholder: 'Message',
          required: true
        });
        radioGroupJ.click(function(event) {
          var extractor, lockType, name, radioButton, _i, _len, _ref;
          lockType = radioGroupJ.find('input[type=radio][name=object_type]:checked')[0].value;
          for (_i = 0, _len = radioButtons.length; _i < _len; _i++) {
            radioButton = radioButtons[_i];
            if (radioButton.value === lockType) {
              _ref = modal.extractors;
              for (name in _ref) {
                extractor = _ref[name];
                if (radioButton.linked.indexOf(name) >= 0) {
                  extractor.div.show();
                } else if (name !== 'object_type') {
                  extractor.div.hide();
                }
              }
            }
          }
        });
        radioGroupJ.click();
        modal.show();
        radioGroupJ.find('input:first').focus();
      };

      Lock.highlightStage = function(color) {
        R.view.backgroundRectangle = new P.Path.Rectangle(P.view.bounds);
        R.view.backgroundRectangle.fillColor = color;
        R.view.backgroundRectangle.sendToBack();
      };

      Lock.unhighlightStage = function() {
        var _ref;
        if ((_ref = R.view.backgroundRectangle) != null) {
          _ref.remove();
        }
        R.view.backgroundRectangle = null;
      };

      Lock.highlightValidity = function(item) {
        this.validatePosition(item, null, true);
      };

      Lock.validatePosition = function(item, bounds, highlight) {
        var lock, locks, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4;
        if (bounds == null) {
          bounds = null;
        }
        if (highlight == null) {
          highlight = false;
        }
        if ((typeof item.getDrawingBounds === "function" ? item.getDrawingBounds() : void 0) > R.rasterizer.maxArea()) {
          if (highlight) {
            R.alertManager.alert('The path is too big.', 'Warning');
          } else {
            return false;
          }
        }
        if (bounds == null) {
          bounds = item.getBounds();
        }
        if ((_ref = R.limitPathV) != null) {
          _ref.strokeColor = 'green';
        }
        if ((_ref1 = R.limitPathH) != null) {
          _ref1.strokeColor = 'green';
        }
        _ref2 = R.locks;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          lock = _ref2[_i];
          lock.unhighlight();
        }
        this.unhighlightStage();
        if (R.view.grid.rectangleOverlapsTwoPlanets(bounds)) {
          if (highlight) {
            if ((_ref3 = R.limitPathV) != null) {
              _ref3.strokeColor = 'red';
            }
            if ((_ref4 = R.limitPathH) != null) {
              _ref4.strokeColor = 'red';
            }
          } else {
            return false;
          }
        }
        locks = Lock.getLocksWhichIntersect(bounds);
        for (_j = 0, _len1 = locks.length; _j < _len1; _j++) {
          lock = locks[_j];
          if (Lock.prototype.isPrototypeOf(item)) {
            if (item !== lock) {
              if (highlight) {
                lock.highlight('red');
              } else {
                return false;
              }
            }
          } else {
            if (lock.getBounds().contains(bounds) && R.me === lock.owner) {
              if (item.lock !== lock) {
                if (highlight) {
                  lock.highlight('green');
                } else {
                  lock.addItem(item);
                }
              }
            } else {
              if (highlight) {
                lock.highlight('red');
              } else {
                return false;
              }
            }
          }
        }
        if (locks.length === 0) {
          if (item.lock != null) {
            if (highlight) {
              this.highlightStage('green');
            } else {
              Item.addItemToStage(item);
            }
          }
        }
        if (Lock.prototype.isPrototypeOf(item)) {
          if (!item.containsChildren()) {
            if (highlight) {
              item.highlight('red');
            } else {
              return false;
            }
          }
        }
        return true;
      };

      Lock.getLockWhichContains = function(rectangle) {
        var lock, _i, _len, _ref;
        _ref = R.locks;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          lock = _ref[_i];
          if (lock.getBounds().contains(rectangle)) {
            return lock;
          }
        }
        return null;
      };

      Lock.getLocksWhichIntersect = function(rectangle) {
        var lock, locks, _i, _len, _ref;
        locks = [];
        _ref = R.locks;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          lock = _ref[_i];
          if (lock.getBounds().intersects(rectangle)) {
            locks.push(lock);
          }
        }
        return locks;
      };

      Lock.initializeParameters = function() {
        var fillColor, parameters, strokeColor, strokeWidth;
        parameters = Lock.__super__.constructor.initializeParameters.call(this);
        strokeWidth = $.extend(true, {}, R.parameters.strokeWidth);
        strokeWidth["default"] = 1;
        strokeColor = $.extend(true, {}, R.parameters.strokeColor);
        strokeColor["default"] = 'black';
        fillColor = $.extend(true, {}, R.parameters.fillColor);
        fillColor["default"] = 'white';
        fillColor.defaultCheck = true;
        fillColor.defaultFunction = null;
        parameters['Style'].strokeWidth = strokeWidth;
        parameters['Style'].strokeColor = strokeColor;
        parameters['Style'].fillColor = fillColor;
        parameters['Options'] = {
          addModule: {
            type: 'button',
            label: 'Link module',
            "default": function() {
              var item, _i, _len, _ref;
              _ref = R.selectedItems;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                item = _ref[_i];
                if (Lock.prototype.isPrototypeOf(item)) {
                  item.askForModule();
                }
              }
            },
            initializeController: function(controller) {
              var firstItem, spanJ, _ref;
              spanJ = $(controller.domElement).find('.property-name');
              firstItem = R.selectedItems[0];
              if ((firstItem != null ? (_ref = firstItem.data) != null ? _ref.moduleName : void 0 : void 0) != null) {
                spanJ.text('Change module (' + firstItem.data.moduleName + ')');
              }
            }
          }
        };
        return parameters;
      };

      Lock.parameters = Lock.initializeParameters();

      function Lock(rectangle, data, pk, owner, date, modulePk) {
        var item, pkString, title, titleJ, _i, _len, _ref, _ref1;
        this.rectangle = rectangle;
        this.data = data != null ? data : null;
        this.pk = pk != null ? pk : null;
        this.owner = owner != null ? owner : null;
        this.date = date;
        this.modulePk = modulePk;
        this.select = __bind(this.select, this);
        this.update = __bind(this.update, this);
        this.saveCallback = __bind(this.saveCallback, this);
        Lock.__super__.constructor.call(this, this.data, this.pk);
        R.locks.push(this);
        this.group.name = 'lock group';
        this.draw();
        R.view.lockLayer.addChild(this.group);
        this.sortedPaths = [];
        this.sortedDivs = [];
        this.itemListsJ = R.templatesJ.find(".layer").clone();
        pkString = '' + (this.pk || this.id);
        pkString = pkString.substring(pkString.length - 3);
        title = "Lock ..." + pkString;
        if (this.owner) {
          title += " of " + this.owner;
        }
        titleJ = this.itemListsJ.find(".title");
        titleJ.text(title);
        titleJ.click((function(_this) {
          return function(event) {
            _this.itemListsJ.toggleClass('closed');
            if (!event.shiftKey) {
              R.tools.select.deselectAll();
            }
            _this.select();
          };
        })(this));
        this.itemListsJ.find('.rDiv-list').sortable({
          stop: Item.zIndexSortStop,
          delay: 250
        });
        this.itemListsJ.find('.rPath-list').sortable({
          stop: Item.zIndexSortStop,
          delay: 250
        });
        this.itemListsJ.mouseover((function(_this) {
          return function(event) {
            _this.highlight();
          };
        })(this));
        this.itemListsJ.mouseout((function(_this) {
          return function(event) {
            _this.unhighlight();
          };
        })(this));
        R.sidebar.itemListsJ.prepend(this.itemListsJ);
        this.itemListsJ = R.sidebar.itemListsJ.find(".layer:first");
        _ref = R.items;
        for (item = _i = 0, _len = _ref.length; _i < _len; item = ++_i) {
          pk = _ref[item];
          if (Lock.prototype.isPrototypeOf(item)) {
            continue;
          }
          if (item.getBounds().intersects(this.rectangle)) {
            this.addItem(item);
          }
        }
        if ((_ref1 = this.data) != null ? _ref1.loadEntireArea : void 0) {
          R.view.entireAreas.push(this);
        }
        if (this.modulePk != null) {
          Dajaxice.draw.getModuleSource(R.initializeModule, {
            pk: this.modulePk,
            accepted: true
          });
        }
        return;
      }

      Lock.prototype.initializeModule = function() {
        var module;
        if (!R.loader.checkError(result)) {
          return;
        }
        module = JSON.parse(result.module);
        R.parentLock = this;
        R.runModule(module);
      };

      Lock.prototype.draw = function() {
        if (this.drawing != null) {
          this.drawing.remove();
        }
        if (this.raster != null) {
          this.raster.remove();
        }
        this.raster = null;
        this.drawing = new P.Path.Rectangle(this.rectangle);
        this.drawing.name = 'rlock background';
        this.drawing.strokeWidth = this.data.strokeWidth > 0 ? this.data.strokeWidth : 1;
        this.drawing.strokeColor = this.data.strokeColor != null ? this.data.strokeColor : 'black';
        this.drawing.fillColor = this.data.fillColor || new P.Color(255, 255, 255, 0.5);
        this.drawing.controller = this;
        this.group.addChild(this.drawing);
      };

      Lock.prototype.setParameter = function(name, value, updateGUI, update) {
        Lock.__super__.setParameter.call(this, name, value, updateGUI, update);
        switch (name) {
          case 'strokeWidth':
          case 'strokeColor':
          case 'fillColor':
            if (this.raster == null) {
              this.drawing[name] = this.data[name];
            } else {
              this.draw();
            }
        }
      };

      Lock.prototype.save = function(addCreateCommand) {
        var args, data, siteData;
        if (addCreateCommand == null) {
          addCreateCommand = true;
        }
        if (R.view.grid.rectangleOverlapsTwoPlanets(this.rectangle)) {
          return;
        }
        if (this.rectangle.area === 0) {
          this.remove();
          R.alertManager.alert("Error: your box is not valid.", "error");
          return;
        }
        data = this.getData();
        siteData = {
          restrictArea: data.restrictArea,
          disableToolbar: data.disableToolbar,
          loadEntireArea: data.loadEntireArea
        };
        args = {
          city: {
            city: R.city
          },
          box: Utils.CS.boxFromRectangle(this.rectangle),
          object_type: this.constructor.object_type,
          data: JSON.stringify(data),
          siteData: JSON.stringify(siteData),
          name: data.name
        };
        Dajaxice.draw.saveBox(this.saveCallback, args);
        Lock.__super__.save.apply(this, arguments);
      };

      Lock.prototype.saveCallback = function(result) {
        R.loader.checkError(result);
        if (result.pk == null) {
          this.remove();
          return;
        }
        this.owner = result.owner;
        this.setPK(result.pk);
        if (this.updateAfterSave != null) {
          this.update(this.updateAfterSave);
        }
        Lock.__super__.saveCallback.apply(this, arguments);
      };

      Lock.prototype.addUpdateFunctionAndArguments = function(args, type) {
        var item, _i, _len, _ref;
        _ref = this.children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          item.addUpdateFunctionAndArguments(args, type);
        }
      };

      Lock.prototype.update = function(type) {
        var args, item, itemsToUpdate, pk, updateBoxArgs, _i, _len, _ref;
        if (this.pk == null) {
          this.updateAfterSave = type;
          return;
        }
        delete this.updateAfterSave;
        if (R.view.grid.rectangleOverlapsTwoPlanets(this.rectangle)) {
          return;
        }
        updateBoxArgs = {
          box: Utils.CS.boxFromRectangle(this.rectangle),
          pk: this.pk,
          object_type: this.object_type,
          name: this.data.name,
          data: this.getStringifiedData(),
          updateType: type,
          modulePk: this.modulePk
        };
        args = [];
        args.push({
          "function": 'updateBox',
          "arguments": updateBoxArgs
        });
        if (type === 'position' || type === 'rectangle') {
          itemsToUpdate = type === 'position' ? this.children() : [];
          _ref = R.items;
          for (pk in _ref) {
            item = _ref[pk];
            if (!Lock.prototype.isPrototypeOf(item)) {
              if (item.lock !== this && this.rectangle.contains(item.getBounds())) {
                this.addItem(item);
                itemsToUpdate.push(item);
              }
            }
          }
          for (_i = 0, _len = itemsToUpdate.length; _i < _len; _i++) {
            item = itemsToUpdate[_i];
            args.push({
              "function": item.getUpdateFunction(),
              "arguments": item.getUpdateArguments()
            });
          }
        }
        Dajaxice.draw.multipleCalls(this.updateCallback, {
          functionsAndArguments: args
        });
      };

      Lock.prototype.updateCallback = function(results) {
        var result, _i, _len;
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          R.loader.checkError(result);
        }
      };

      Lock.prototype.deleteFromDatabase = function() {
        Dajaxice.draw.deleteBox(R.loader.checkError, {
          'pk': this.pk
        });
      };

      Lock.prototype.setRectangle = function(rectangle, update) {
        if (update == null) {
          update = true;
        }
        Lock.__super__.setRectangle.call(this, rectangle, update);
        Utils.Rectangle.updatePathRectangle(this.drawing, rectangle);
      };

      Lock.prototype.moveTo = function(position, update) {
        var delta, item, _i, _len, _ref;
        delta = position.subtract(this.rectangle.center);
        _ref = this.children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          item.rectangle.center.x += delta.x;
          item.rectangle.center.y += delta.y;
          if (Item.Div.prototype.isPrototypeOf(item)) {
            item.updateTransform();
          }
        }
        Lock.__super__.moveTo.call(this, position, update);
      };

      Lock.prototype.containsChildren = function() {
        var item, _i, _len, _ref;
        _ref = this.children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (!this.rectangle.contains(item.getBounds())) {
            return false;
          }
        }
        return true;
      };

      Lock.prototype.showChildren = function() {
        var item, _i, _len, _ref, _ref1;
        _ref = this.children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if ((_ref1 = item.group) != null) {
            _ref1.visible = true;
          }
        }
      };

      Lock.prototype.select = function(updateOptions) {
        var item, _i, _len, _ref;
        if (updateOptions == null) {
          updateOptions = true;
        }
        if (!Lock.__super__.select.call(this, updateOptions) || this.owner !== R.me) {
          return false;
        }
        _ref = this.children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          item.deselect();
        }
        return true;
      };

      Lock.prototype.remove = function() {
        var path, _i, _len, _ref;
        _ref = this.children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          path = _ref[_i];
          this.removeItem(path);
        }
        this.itemListsJ.remove();
        this.itemListsJ = null;
        Utils.Array.remove(R.locks, this);
        this.drawing = null;
        Lock.__super__.remove.apply(this, arguments);
      };

      Lock.prototype.children = function() {
        return this.sortedDivs.concat(this.sortedPaths);
      };

      Lock.prototype.addItem = function(item) {
        Item.addItemTo(item, this);
        item.lock = this;
      };

      Lock.prototype.removeItem = function(item) {
        Item.addItemToStage(item);
        item.lock = null;
      };

      Lock.prototype.highlight = function(color) {
        Lock.__super__.highlight.call(this);
        if (color) {
          this.highlightRectangle.fillColor = color;
          this.highlightRectangle.strokeColor = color;
          this.highlightRectangle.dashArray = [];
        }
      };

      Lock.prototype.askForModule = function() {
        Dajaxice.draw.getModuleList(this.createSelectModuleModal);
      };

      Lock.prototype.createSelectModuleModal = function(result) {};

      Lock.prototype.addModule = function() {};

      return Lock;

    })(Item);
    Website = (function(_super) {
      __extends(Website, _super);

      Website.label = 'Website';

      Website.object_type = 'website';

      function Website(rectangle, data, pk, owner, date) {
        this.rectangle = rectangle;
        this.data = data != null ? data : null;
        this.pk = pk != null ? pk : null;
        this.owner = owner != null ? owner : null;
        if (date == null) {
          date = null;
        }
        Website.__super__.constructor.call(this, this.rectangle, this.data, this.pk, this.owner, date);
        return;
      }

      Website.prototype.enableInteraction = function() {};

      return Website;

    })(Lock);
    VideoGame = (function(_super) {
      __extends(VideoGame, _super);

      VideoGame.label = 'Video game';

      VideoGame.object_type = 'video-game';

      function VideoGame(rectangle, data, pk, owner, date) {
        this.rectangle = rectangle;
        this.data = data != null ? data : null;
        this.pk = pk != null ? pk : null;
        this.owner = owner != null ? owner : null;
        if (date == null) {
          date = null;
        }
        VideoGame.__super__.constructor.call(this, this.rectangle, this.data, this.pk, this.owner, date);
        this.currentCheckpoint = -1;
        this.checkpoints = [];
        return;
      }

      VideoGame.prototype.getData = function() {
        var data;
        data = VideoGame.__super__.getData.call(this);
        data.loadEntireArea = true;
        return data;
      };

      VideoGame.prototype.enableInteraction = function() {};

      VideoGame.prototype.initGUI = function() {
        console.log("Gui init");
      };

      VideoGame.prototype.updateGame = function(tool) {
        var checkpoint, _i, _len, _ref;
        _ref = this.checkpoints;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          checkpoint = _ref[_i];
          if (checkpoint.contains(tool.car.position)) {
            if (this.currentCheckpoint === checkpoint.data.checkpointNumber - 1) {
              this.currentCheckpoint = checkpoint.data.checkpointNumber;
              if (this.currentCheckpoint === 0) {
                this.startTime = Date.now();
                R.alertManager.alert("Game started, go go go!", "success");
              } else {
                R.alertManager.alert("Checkpoint " + this.currentCheckpoint + " passed!", "success");
              }
            }
            if (this.currentCheckpoint === this.checkpoints.length - 1) {
              this.finishGame();
            }
          }
        }
      };

      VideoGame.prototype.finishGame = function() {
        var time;
        time = (Date.now() - this.startTime) / 1000;
        R.alertManager.alert("You won ! Your time is: " + time.toFixed(2) + " seconds.", "success");
        this.currentCheckpoint = -1;
      };

      return VideoGame;

    })(Lock);
    Link = (function(_super) {
      __extends(Link, _super);

      Link.label = 'Link';

      Link.modalTitle = "Insert a hyperlink";

      Link.modalTitleUpdate = "Modify your link";

      Link.object_type = 'link';

      Link.initializeParameters = function() {
        var parameters;
        parameters = Link.__super__.constructor.initializeParameters.call(this);
        delete parameters['Lock'];
        return parameters;
      };

      Link.parameters = Link.initializeParameters();

      function Link(rectangle, data, pk, owner, date) {
        var _ref;
        this.rectangle = rectangle;
        this.data = data != null ? data : null;
        this.pk = pk != null ? pk : null;
        this.owner = owner != null ? owner : null;
        if (date == null) {
          date = null;
        }
        Link.__super__.constructor.call(this, this.rectangle, this.data, this.pk, this.owner, date);
        if ((_ref = this.linkJ) != null) {
          _ref.click((function(_this) {
            return function(event) {
              var location, p, pos;
              if (_this.linkJ.attr("href").indexOf("http://romanesc.co/#") === 0) {
                location = _this.linkJ.attr("href").replace("http://romanesc.co/#", "");
                pos = location.split(',');
                p = new P.Point();
                p.x = parseFloat(pos[0]);
                p.y = parseFloat(pos[1]);
                R.view.moveTo(p, 1000);
                event.preventDefault();
                return false;
              }
            };
          })(this));
        }
        return;
      }

      return Link;

    })(Lock);
    Item.Lock = Lock;
    Item.Link = Link;
    Item.Website = Website;
    Item.VideoGame = VideoGame;
    return Lock;
  });

}).call(this);
